services:
  data-collector:
    image: mda-new
    volumes:
      - mda:/data
    command: python app/src/step1_data_extraction.py
  
  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - mda:/data
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --allowed-hosts "*"
      --cors-allowed-origins "*"
      --backend-store-uri sqlite:////data/mlflow.db
      --default-artifact-root /data/mlartifacts 

  model-calibrator:
    image: mda-new
    depends_on:
      - mlflow
    volumes:
      - mda:/data
    command: python app/src/step2_lightgbm_2y.py

  airflow-init:
    image: apache/airflow:2.9.3
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "airflow db migrate &&
      airflow users create -u admin -p admin -f Wingo -l Ng -r Admin -e wingfungwingo.ng@student.kuleuven.be || true"

  airflow-server:
    image: apache/airflow:2.9.3
    ports:
      - "8080:8080"
    volumes:
      - airflow_home:/opt/airflow
      - ./dags:/opt/airflow/dags
    depends_on:
      - airflow-init
    command: airflow webserver

  airflow-scheduler:
    image: apache/airflow:2.9.3
    volumes:
      - airflow_home:/opt/airflow
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dags:/opt/airflow/dags
    depends_on:
      - airflow-init
    command: airflow scheduler

volumes:
  mda:
  airflow_home:

networks:
  default:
    name: mda-net
